#cloud-config
---
package_update: true
package_upgrade: true

runcmd:
  # Load necessary kernel modules
  - echo "Loading kernel modules"
  - |
    cat <<EOF | tee /etc/modules-load.d/k8s.conf
    overlay
    br_netfilter
    EOF
  - modprobe overlay
  - modprobe br_netfilter

  # Setup networking
  - echo "Setting up networking for Kubernetes"
  - |
    cat <<EOF | tee /etc/sysctl.d/k8s.conf
    net.bridge.bridge-nf-call-iptables  = 1
    net.bridge.bridge-nf-call-ip6tables = 1
    net.ipv4.ip_forward                 = 1
    EOF
  - sysctl --system

  # Disable swap as required by Kubernetes
  - echo "Disabling swap"
  - swapoff -a
  - sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
