---
- name: Gather facts from Hetzner Cloud servers
  hosts: all
  vars:
    ansible_user: ubuntu
  tasks:
    - name: Gather facts
      ansible.builtin.setup:
    - name: Display hostname
      debug:
        msg: "{{ inventory_hostname }}"
    - ping:
