---
- name: Gather facts from Hetzner Cloud servers
  hosts: all
  tasks:
    - name: Gather facts
      ansible.builtin.setup:
    - name: Display hostname
      debug:
        msg: "{{ inventory_hostname }}"
    - ping:
    - name: Run the id command as root
      become: yes 
      command: id
      register: result
    - name: Display the output of id command
      debug:
        var: result.stdout
